### Importing Numpy Library

In [1]:
import numpy as np

### Arrays filled with zeros

In [10]:
arr_zero = np.zeros(5)
print(arr_zero)

[0. 0. 0. 0. 0.]


In [11]:
arr_zero1 = np.zeros((3,4))
print(arr_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
arr_zero2 = np.zeros((3,3,4))
print(arr_zero2)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### Array filled with one

In [18]:
arr_one = np.ones(5)
print(arr_one)

[1. 1. 1. 1. 1.]


In [19]:
arr_one1 = np.ones((2,3))
print(arr_one1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
arr_one2 = np.ones((3,2,3))
print(arr_one2)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


### Creating an empty array

In [23]:
arr_em = np.empty(5)
print(arr_em)

[1. 1. 1. 1. 1.]


### Array with a range of elements

In [24]:
arr_rn = np.arange(5)
print(arr_rn)

[0 1 2 3 4]


### Diagonal elements filled with one

In [25]:
arr_diag = np.eye(3)
print(arr_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
arr_diag1 = np.eye(5,5)
print(arr_diag1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Array with values separated in a specified interval

In [36]:
arr_lin = np.linspace(10, 20, num=5)
print(arr_lin)

[10.  12.5 15.  17.5 20. ]
