### Importing Numpy Library

In [1]:
import numpy as np

### Data types of Numpy array

In [3]:
ar = np.array([3,7,4,8,9])
print("The data type is: ", ar.dtype)

The data type is:  int32


In [4]:
ar1 = np.array([3.9, 7.8, 4.2, 8.1, 9.5])
print("The data type is: ", ar1.dtype)

The data type is:  float64


In [5]:
ar2 = np.array(['S','A','B','T','Y'])
print("The data type is: ", ar2.dtype)

The data type is:  <U1


In [7]:
ar3 = np.array([1, 'David', 27])
print("The data type is: ", ar3.dtype)

The data type is:  <U11


### Converting one data type to another

In [9]:
ar_new = np.array([3,7,4,8,9], dtype = np.int8)
print("The new data type is: ", ar_new.dtype)
print(ar_new)

The new data type is:  int8
[3 7 4 8 9]


In [10]:
ar_new1 = np.array([3,7,4,8,9], dtype = 'f')
print("The new data type is: ", ar_new1.dtype)
print(ar_new1)

The new data type is:  float32
[3. 7. 4. 8. 9.]


In [13]:
v = np.array([2,3,4,5])
v_new = np.float32(v)

print("Previous data type is:", v.dtype)
print(v)
print("New data type is:", v_new.dtype)
print(v_new)

Previous data type is: int32
[2 3 4 5]
New data type is: float32
[2. 3. 4. 5.]


### Direct conversion using astype() function

In [15]:
var = np.array([2,3,4,5])
New_var = var.astype(complex)

print("Previous data type is:", var.dtype)
print(var)
print("New data type is:", New_var.dtype)
print(New_var)

Previous data type is: int32
[2 3 4 5]
New data type is: complex128
[2.+0.j 3.+0.j 4.+0.j 5.+0.j]
