### Importing Numpy Library

In [1]:
import numpy as np

### Difference between list and array

In [8]:
L = [7,2,8,3,4,9]
print(L, "The type is: ", type(L))

[7, 2, 8, 3, 4, 9] The type is:  <class 'list'>


In [9]:
ar = np.array([7,2,8,3,4,9])
print(ar, "The type is: ", type(ar))

[7 2 8 3 4 9] The type is:  <class 'numpy.ndarray'>


In [10]:
%timeit [j**4 for j in range(1,9)] # Execution time of a list

12.2 µs ± 446 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
%timeit np.arange(1,9)**4 # Execution time of an array

34.6 µs ± 605 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Creating array

In [14]:
# From list to array
y = [5,6,7,8]
ar1 = np.array(y)

print(ar1, type(ar1), sep='\n')

[5 6 7 8]
<class 'numpy.ndarray'>


In [16]:
# Take values from user and create an array
L = []
for i in range(5):
    j = int(input("Enter a value:"))
    L.append(j)

Arr = np.array(L)
print(L, type(L), Arr, type(Arr), sep='\n')

Enter a value: 7
Enter a value: 4
Enter a value: 8
Enter a value: 3
Enter a value: 5


[7, 4, 8, 3, 5]
<class 'list'>
[7 4 8 3 5]
<class 'numpy.ndarray'>


### Checking dimension of array

In [27]:
A1 = np.array([10,20,30,40])
print(A1)
print("Dimension is:",A1.ndim)

[10 20 30 40]
Dimension is: 1


In [28]:
A2 = np.array([[10,20,30],[40,50,60]])
print(A2)
print("Dimension is:",A2.ndim)

[[10 20 30]
 [40 50 60]]
Dimension is: 2


In [29]:
A3 = np.array([[[10,20,30],[40,50,60],[70,80,90]]])
print(A3)
print("Dimension is:",A3.ndim)

[[[10 20 30]
  [40 50 60]
  [70 80 90]]]
Dimension is: 3


In [33]:
# Multidimensional array
Ar = np.array([4,3,5,9,7], ndmin = 7)
print(Ar)
print("Dimension is:", Ar.ndim)

[[[[[[[4 3 5 9 7]]]]]]]
Dimension is: 7
