# Arrays with random numbers

### Importing Numpy Library

In [1]:
import numpy as np

### rand() function

In [5]:
var = np.random.rand(5)
print(var)

[0.37666171 0.50534764 0.59574483 0.02604839 0.79022093]


In [6]:
var1 = np.random.rand(2,5)
print(var1)

[[0.49640612 0.00717191 0.04046985 0.58788184 0.33573918]
 [0.35163842 0.98715759 0.76799447 0.71199493 0.74342157]]


In [7]:
var2 = np.random.rand(2,3,2)
print(var2)

[[[0.87051604 0.66665609]
  [0.00822937 0.88947543]
  [0.39098524 0.58068499]]

 [[0.80975038 0.83933614]
  [0.83650309 0.79823331]
  [0.66440524 0.35070099]]]


### randn() function

In [10]:
Var = np.random.randn(5)
print(Var)

[ 1.69739409 -0.27068365 -0.50359792 -0.60396698 -0.26371552]


In [11]:
Var1 = np.random.randn(3,4)
print(Var1)

[[ 0.25942749 -0.5801693   0.53338072 -0.21764586]
 [-1.40401704 -0.82336286 -0.42294977 -0.07462039]
 [-0.40780172 -0.13077675 -0.39043111  0.38926068]]


In [15]:
Var2 = np.random.randn(3,3,3)
print(Var2)

[[[-1.64628587  0.3236123  -2.41036028]
  [ 0.16410171  0.51913355 -0.50057218]
  [ 0.72552766 -1.33919478 -0.04455912]]

 [[-1.251155   -0.58435631 -1.21548952]
  [ 0.64810829 -0.53171821 -0.11045925]
  [ 0.15705388  0.82008495  1.49956625]]

 [[ 2.21301568 -1.36150333  1.28322756]
  [ 0.96100579  0.18089603 -0.72813246]
  [-1.20354577  0.95123724 -1.70554301]]]


### ranf() function

In [16]:
v = np.random.ranf(4)
print(v)

[0.87023626 0.23538629 0.16018447 0.75335217]


In [18]:
v1 = np.random.ranf((4,3))
print(v1)

[[0.36582285 0.70903738 0.45941671]
 [0.57200879 0.8407742  0.67144017]
 [0.48532242 0.73420664 0.40334614]
 [0.32201783 0.03322899 0.54966121]]


### randint() function

In [19]:
V = np.random.randint(5, 25, 4) # Min, Max, Total value
print(V)

[10  7  6 21]
